/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package agenda.gui;

import agenda.io.AgendaIO;
import java.awt.BorderLayout;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lucio
 */
public class ListarEventosPanel extends javax.swing.JPanel {

    private JTable table;

    private Vector<String> getNameColumns() {
        Vector<String> nameColumns = new Vector<>();
        nameColumns.add("Data");
        nameColumns.add("Descrição");
        nameColumns.add("Periodicidade");
        nameColumns.add("E-mail");
        nameColumns.add("Alarme");
        return nameColumns;
    }

    private Vector<Vector<Object>> getDataColumns() {
		AgendaIO io = new AgendaIO();
		Vector<Vector<Object>> dataColumns = null;

		try {
			dataColumns = io.getEventos();
		} catch (Exception ex) {
			JOptionPane.showMessageDialog(null, "ERRO", ex.getMessage(),
					JOptionPane.ERROR_MESSAGE);
		}

		return dataColumns;
	}

    
    public void addNewRow(Object[] valores) {
        ((DefaultTableModel) table.getModel()).addRow(valores);
    }

    public ListarEventosPanel() {
        initComponents();

        setLayout(new BorderLayout(0, 0));

        table = new JTable(getDataColumns(), getNameColumns());
        JScrollPane scroll = new JScrollPane(table);
        add(scroll, BorderLayout.CENTER);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
